/**
 * Vite Configuration File
 * Note: This is a boilerplate template automatically generated by Vite.
 * It strictly handles compiling and bundling React via the `@vitejs/plugin-react`.
 */
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
})
