DROP TABLE IF EXISTS library CASCADE;
DROP TABLE IF EXISTS book CASCADE;
DROP TABLE IF EXISTS student CASCADE;

CREATE TABLE student (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  class VARCHAR(100) NOT NULL,
  photo_url TEXT,
  video_url TEXT
);

CREATE TABLE book (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  author VARCHAR(255),
  pub VARCHAR(255),
  year DATE NOT NULL
);

CREATE TABLE library (
  id SERIAL PRIMARY KEY,
  student_id INTEGER REFERENCES student(id),
  book_id INTEGER REFERENCES book(id),
  start_date DATE NOT NULL,
  end_date DATE NOT NULL
);